import Head from "next/head";
import LandingPage from "@/components/landing-page";
import { useState } from "react";
import Link from "next/link";
import "/src/styles/globals.css";

export default function Home() {
  const [data, setData] = useState<string | any>();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <nav>
          <ul>
            <li>
              <Link href="/api/graphql">GraphiQL</Link>
            </li>
            <li>
              <a href="#">Github</a>
            </li>
          </ul>
        </nav>
        {data ? (
          <div className="main-content">
            <h2>Showing results for {data}</h2>
            <div className="card">content wrapper</div>
          </div>
        ) : (
          <LandingPage setData={setData} />
        )}
        <footer>
          <span>❮❯ by</span>&nbsp;
          <a href="https://github.com/Stephany-Doris"> Stephany Doris</a>
        </footer>
      </main>
    </>
  );
}
